language: python
matrix:
  include:
  - python: 2.7
    env:
    - secure: "ODiqrFe+QkcEg2l4Cu9gn4XRMWjXdOlIuJpcf0GTxpc8qf2US90qhqAqBWhv93m8v6+IcFEa0lAucg/kxNiO3/KJa+ia6E6Sjy21dAvtIUxOxeB4kZlJrn7p+dCc+brZq0ha6fGPaVFVGp4BDgewezFsp5diflWmjqy4tcVZvB5jDbCrtLDtJ8k6VR3xU/8Sjia+7ubeY+xK/32ihJmPsU1Xv1pnq87cJQCzgnx21Xf5c+LLjj1hfk5HAY7Z8B5c9e3wXq36/fZSvgvkEOFRFdzICgm8OwEw1/VfOslPml3G9PECL0S40qN/RDz0iniw0au6oKSW6kIUGgwo+x37rAMM9WIKcAYjj59StYtmCWF1qUojFQMDKauX8BUM7X8DdE224jY23JBgVoaLP45vzwogHq7IluPMufyVuj8r6lxrUJnTxaL6fFcuZbLDAIQhvuPtbNoJLjHWxRAH8U11rdTDXC9urUep10dRjF/6tY9PoNMQdAuTHlN1uleFiaXlkHhX41utnSlxZUWyFW0o55wuHllPoPfCofynGx394t2hjP8nBQkAJid7nYOhQF1WyPSRomy795xPdlbN5HQLrGw7BKd+C+lgivyqryAJUk5+PZMjdYO281eCZ1lhJQdDaenu1kg4E4zT2sAmO9ZqtGig1rD2oqghLwotabdTnv4="
    - secure: "UtcRGkgVAwYpTZSP8A8lN8GGDQ0VBar1CvDo68yfMjAtcLb+VxkULn/uSc+HrHTGIz/AIcd5cwkrfcELSngQVZDOd+3aTSyJKoxUIo/kh+uAh89a/gNVPEvshsokTO2P2jSj6Vu279X76f43rq90ZITABrjo1ucaZlEV7QguZpMr6aJ8duvMA1iejf/oEYz/iztNiAWhuir6jPnDKpehOTKYy/csqCE0Biwx1qN1fUYL50F5uWrSOjZ5hHd2j6tGoFSmEDmFNgGNU+RTRwdDkCKVi5G7RIbdMmSVqHyAlqSPmpP7dcDOhPf8MZnB51lW3ZxPRkxgXmDuvpaIDbG/jVqmr2+lV8mHAJdd1u1VN+b1URaVnIrPmkwP7GvGtdwcj5BgC+iRgqSV2B8qlr4Dv8z8tnJT9TTLJxVi+18NPsIGM4IdAgAxj9SsHe70zB76Wu4ouqtJfuDXewiE5kmecNhW2y7Mo8NwG2IVb67MNB41FE8XYIlgtjnKRZBATPn6kDdr6Dj+jVF+ROq6rZwbS7y6cZBKjqsG5L8czhxh41oDYp0HtF2mvfb1ApPTmcyOvYOIN4XSZqN5NpfPheL9qfKbBnu/ar8Tsc68forRs8dFOTxBODsimrRdbQUGztqjU4GP4pgDOUE65WRkksBqw5ehqdRZVekeZmp4kxHoc4w="
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
    - BOB_UPLOAD_WHEEL="--universal"
  - python: 3.3
  - python: 3.4
  - python: 3.5
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libvl-dev libjpeg8-dev libnetpbm10-dev libpng12-dev libtiff4-dev libgif-dev
- sudo apt-get install -qq --force-yes libhdf5-serial-dev libvl-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended gfortran
- sudo apt-get install -qq --force-yes libatlas-dev libatlas-base-dev liblapack-dev
- pip install --upgrade pip
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy scipy matplotlib coverage cpp-coveralls
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- ./bin/buildout buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/coverage run --source=bob.ip.skincolorfilter ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
